2025-05-18 02:04:43,677 - DeeperHubMain - INFO - Iniciando cliente interativo - Conectando a localhost:4000
2025-05-18 02:06:18,731 - DeeperHubMain - CRITICAL - Erro inesperado no cliente interativo: 
2025-05-18 02:06:18,734 - DeeperHubMain - DEBUG - Traceback (most recent call last):
  File "C:\deeper_hub\test_python\deeper_hub_client.py", line 164, in run_interactive_client
    
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError

